package inpdf;

public enum DocumentType {
	UNKNOWN,
	BOLETO_BANCARIO_BANCO_DO_BRASIL,
	BOLETO_BANCARIO_BANRISUL,
	BOLETO_BANCARIO_BRADESCO,
	BOLETO_BANCARIO_ITAU,
	BOLETO_BANCARIO_SANTANDER,
	BOLETO_BANCARIO_SICREDI,
	DECLARACAO_IMPOSTO_DE_RENDA
}