package inpdf.irpf;

public enum IRSectionsEnum {
	IDENTIFICACAO_CONTRIBUINTE("IDENTIFICAÇÃO DO CONTRIBUINTE"),
	RENDIMENTOS_TRIBUTAVEIS_PJ_TITULAR("RENDIMENTOS TRIBUTÁVEIS RECEBIDOS DE PESSOA JURÍDICA PELO TITULAR"),
	RENDIMENTOS_ISENTOS_NAO_TRIBUTAVEIS("RENDIMENTOS ISENTOS E NÃO TRIBUTÁVEIS"),
	RENDIMENTOS_TRIBUTACAO_EXCLUSIVA("RENDIMENTOS SUJEITOS À TRIBUTAÇÃO EXCLUSIVA / DEFINITIVA"),
	RENDIMENTOS_ACUMULADOS_PJ_TITULAR("RENDIMENTOS TRIBUTÁVEIS DE PESSOA JURÍDICA RECEBIDOS ACUMULADAMENTE PELO TITULAR"),
	IMPOSTO_PAGO_RETIDO("IMPOSTO PAGO / RETIDO"),
	PAGAMENTOS_EFETUADOS("PAGAMENTOS EFETUADOS"),
	BENS_DIREITOS("DECLARAÇÃO DE BENS E DIREITOS"),
	DIVIDAS_ONUS("DÍVIDAS E ÔNUS REAIS"),
	RESUMO_DECLARACAO("RESUMO");
	
	public String str;
	
	IRSectionsEnum(String str) {
		this.str = str;
	}	
}